### PR TITLE
adds no thanks button, callback function to close window and button s…

### PR DESCRIPTION
**Pull request by vincenttern**
…ize to Congratulations.py

__What issue are you solving? (Give #issuenumber)__

* Answer here.
The pop window only have a share button and needed a no thanks button, so I added a button that says no thanks. Also, I included a callback function to close the window once the no thanks button is clicked and attribute to make both the button the same size. 

__How do you solve it? (please write this so a human can understand it - bulletpoints are okay)__

* Answer here.
 

- To add the no thanks button, inside the Congrulations.py file I made another button under the share button with the same attributes besides command. The no thanks button command attribute is equal to the close_tkinker_close function that I made so it will close the window when the no thanks button is clicked. Then to make the buttons the same size I added a variable name BTTN_WIDTH that is equal to 18 and added a new attribute name width that is equal to BTTN_WIDTH that is inside the two buttons. 

__If there is something specific in your solution, that you would like the reviewer to give feedback on, tell us here:__

* Answer here.

_If this is your first pull request to the prog-o-meter project, we would really appreciate it if you would fill out this Google form.
This lets us know more about our contributors, and what we can do to make it easier and nicer to contribute to the prog-o-meter project.
Please submit your answer [here](https://docs.google.com/forms/d/e/1FAIpQLSdQqs9shjcyJTTqbkKjGv85Irxxaljvw0H357zuyrRwXq9_nA/viewform?usp=sf_link) and put an 'x' in the box below._

- [x] It is my first pull request to prog-o-meter, and I have answered the survey
- [ ] This is not my first contribution to the prog-o-meter

### CODE REVIEW

**Comment by lineaba** [comment]
Hi @vincenttern thank you so much for your contribution. Unfortunately, someone else have already solved this problem, so I cannot merge your code in. When looking at issues it is always a good idea to check if someone else have said in the comments that they wanted to work on that issue. I hope you find something else you would like to work on. Let me know if you would like some help finding an issue to get started on :)

**Comment by vincenttern** [comment]
Hi Linea,

Sorry, I have no idea open source is like that. So, if I want to contribute
to an open source I would have to ask first?

**Comment by lineaba** [comment]
There is no rule that you have to ask, generally anyone can contribute
anything they want, but there is no guarantee that your code is merged.
Merging code means taking what someone has written and add it into the
project. If you want your contributions to be merged it is important that
no one else have already added the same code. This was what happened in
this case. Another contributor had seen the issue, and written a comment
saying they were gonna start working on that.
Therefore, if you find an issue that you would like to work on, first check
that no one else have written a comment saying they are working on it. If
no one else is working on it, you can write a comment saying that you are
gonna start working on it. You do not need to wait for permission to get
started, but by adding a comment, you make it easier for others to see
which issues they can start working on. ¨
I hope this make sense, if you have any other questions, please let me know
:)


2018-06-03 22:20 GMT-07:00 Vincent Tern <notifications@github.com>:

> Hi Linea,
>
> Sorry, I have no idea open source is like that. So, if I want to contribute
> to an open source I would have to ask first?
>

**Comment by vincenttern** [comment]
Okay, I see. I will definitely contact you if there are any questions that
come up.

Thank You!

**Pull request closed without merging**
